[package]
name = "CLIFileEncryptorDecryptor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
thiserror = "1.0"
zeroize = "1.7"
